### PR TITLE
fix: poetry gh actions

### PR DESCRIPTION
**Pull request by ba11b0y**
Extends #63

### CODE REVIEW

**Comment by ba11b0y** [comment]
Unit tests for poetry would fail unless we setup poetry, this PR aims to add support for the same.

**Comment by nishakm** [comment]
@ba11b0y can you rebase your changes on top of main?

**Comment by ba11b0y** [comment]
@nishakm I've rebased the other branch on top of `main`

https://github.com/opensbom-generator/parsers/pull/63
This PR is based off of #63 to add support for gh actions. Which PR do you think should be merged first?

**Comment by ba11b0y** [comment]
> @ba11b0y can you rebase your changes on top of main?

Done

**Comment by nishakm** [comment]
> > @ba11b0y can you rebase your changes on top of main?
> 
> Done

If you look at the [commits](https://github.com/opensbom-generator/parsers/pull/64/commits) you'll see there are 2 commits which are the ones I had squashed and merged. The last commit you had merged main into your branch. What I would like is for you to take 2 of your commits in the middle and place them on top of main.

I would recommend you set up your local git clone [this way](https://github.com/nishakm/puns#how-to-submit-prs-with-your-github-fork)

**Comment by ba11b0y** [comment]
Yup I have the upstream configured. I merged instead of rebasing 🤦‍♂️ 
Should I go ahead and open a new PR with just the GitHub workflow fix?

**Comment by ba11b0y** [comment]
https://github.com/nishakm/puns#how-to-submit-prs-with-your-github-fork
Nice read! Thanks for sharing!

**Comment by ba11b0y** [comment]
https://github.com/opensbom-generator/parsers/pull/65 adds support for poetry tests. Closing this

**Pull request closed without merging**
